import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    page: {
        flex: 1,
        backgroundColor: "#fffbe6",
        padding: 16,
    },
    header: {
        alignItems: "center",
        gap: 12,
        marginBottom: 20,
    },
    logoContainer: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    logo: {
        height: 60,
        width: 60,
        resizeMode: "contain",
    },
    brandName: {
        fontWeight: "700",
        fontSize: 24,
        color: "#2e7d32",
    },
    controls: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "center",
        gap: 8,
        marginTop: 10,
    },
    button: {
        backgroundColor: "#4caf50",
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 6,
    },
    buttonText: {
        color: "#fff",
        fontWeight: "600",
    },
    activeButton: {
        backgroundColor: "#ffc107",
    },
    logoutBtn: {
        borderWidth: 2,
        borderColor: "#d32f2f",
        borderRadius: 6,
        paddingVertical: 8,
        paddingHorizontal: 14,
        backgroundColor: "#fff",
    },
    logoutText: {
        color: "#d32f2f",
        fontWeight: "600",
    },
    main: {
        flex: 1,
        //flexDirection: "row",
        //justifyContent: "space-between",
        //alignItems: "flex-start",
        //gap: 16,
    },
    cardArea: {
        flex: 1,
        //height: 650,
        borderWidth: 2,
        borderColor: "#ddd",
        borderRadius: 10,
        padding: 8,
    },
    cardContent: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "flex-start",
        gap: 16,
        paddingBottom: 20,
        flexGrow: 1,
    },
    card: {
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 8,
        flexBasis: "47%",
        padding: 12,
        elevation: 3,
    },
    address: {
        textAlign: "center",
        fontWeight: "600",
        marginBottom: 8,
    },
    addressDetail: {
        textAlign: "center",
        fontSize: 12,
        color: "#666",
        marginBottom: 8,
        marginTop: -4,
    },
    image: {
        width: "100%",
        height: 150,
        borderRadius: 6,
        marginBottom: 6,
    },
    actions: {
        alignItems: "center",
    },
    seeBtn: {
        backgroundColor: "#4caf50",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 6,
    },
    seeBtnText: {
        color: "#fff",
        fontWeight: "600",
    },
    detail: {
        flex: 1, // Ocupa todo el espacio de 'main'
        borderWidth: 2,
        borderColor: "#cfcfcf",
        borderRadius: 10,
        padding: 16,
        backgroundColor: "#fff",
        justifyContent: "flex-start",
    },
    detailEmpty: {
        color: "#777",
        textAlign: "center",
    },
    detailTitle: {
        fontWeight: "700",
        fontSize: 20,
        textAlign: "center",
        marginBottom: 8,
    },
    detailDireccion: {
        fontWeight: "600",
        fontSize: 18,
        textAlign: "center",
        marginBottom: 8,
    },
    detailSubtitle: {
        fontWeight: "600",
        fontSize: 16,
        marginTop: 12,
        marginBottom: 6,
    },
    detailItem: {
        fontSize: 15,
        color: "#444",
        marginLeft: 8,
        marginBottom: 2,
    },
    footer: {
        flexDirection: "row",
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: 10,
        marginTop: 16,
    },
    btnPrimary: {
        backgroundColor: "#4caf50",
        borderRadius: 8,
        paddingVertical: 10,
        paddingHorizontal: 18,
        flex: 1,
        alignItems: 'center',
    },
    btnText: {
        color: "#fff",
        fontWeight: "600",
    },
    btnGhost: {
        backgroundColor: "#d32f2f",
        borderWidth: 2,
        borderColor: "#d32f2f",
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 18,
        flex: 1,
        alignItems: 'center',
    },
    btnGhostText: {
        color: "#fff",
        fontWeight: "600",
    },
    btnSecondary: {
        backgroundColor: "#6c757d", // Un color gris/secundario
        borderRadius: 8,
        paddingVertical: 10,
        paddingHorizontal: 18,
        flex: 1,
        alignItems: 'center',
    },
});
